ConditionsSupportsApplicationsForm.create!(
  [
    ##私立幼稚園等保護者補助金-生活保護-第一子
    { id: 1, application_form_id: 1, conditions_support_id: 2},
    { id: 2, application_form_id: 1, conditions_support_id: 3},
    { id: 3, application_form_id: 2, conditions_support_id: 3},
    { id: 4, application_form_id: 1, conditions_support_id: 4},
    { id: 5, application_form_id: 3, conditions_support_id: 4},
    { id: 6, application_form_id: 1, conditions_support_id: 5},
    { id: 7, application_form_id: 2, conditions_support_id: 5},
    { id: 8, application_form_id: 3, conditions_support_id: 5},
    ##私立幼稚園等保護者補助金-生活保護-第二子
    { id: 9, application_form_id: 1, conditions_support_id: 6},
    { id: 10, application_form_id: 1, conditions_support_id: 7},
    { id: 11, application_form_id: 2, conditions_support_id: 7},
    { id: 12, application_form_id: 1, conditions_support_id: 8},
    { id: 13, application_form_id: 3, conditions_support_id: 8},
    { id: 14, application_form_id: 1, conditions_support_id: 9},
    { id: 15, application_form_id: 2, conditions_support_id: 9},
    { id: 16, application_form_id: 3, conditions_support_id: 9},
    ##私立幼稚園等保護者補助金-生活保護-第三子
    { id: 17, application_form_id: 1, conditions_support_id: 10},
    { id: 18, application_form_id: 1, conditions_support_id: 11},
    { id: 19, application_form_id: 2, conditions_support_id: 11},
    { id: 20, application_form_id: 1, conditions_support_id: 12},
    { id: 21, application_form_id: 3, conditions_support_id: 12},
    { id: 22, application_form_id: 1, conditions_support_id: 13},
    { id: 23, application_form_id: 2, conditions_support_id: 13},
    { id: 24, application_form_id: 3, conditions_support_id: 13},
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第一子
    { id: 25, application_form_id: 1, conditions_support_id: 14},
    { id: 26, application_form_id: 1, conditions_support_id: 15},
    { id: 27, application_form_id: 2, conditions_support_id: 15},
    { id: 28, application_form_id: 1, conditions_support_id: 16},
    { id: 29, application_form_id: 3, conditions_support_id: 16},
    { id: 30, application_form_id: 1, conditions_support_id: 17},
    { id: 31, application_form_id: 2, conditions_support_id: 17},
    { id: 32, application_form_id: 3, conditions_support_id: 17},
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第二子
    { id: 33, application_form_id: 1, conditions_support_id: 18},
    { id: 34, application_form_id: 1, conditions_support_id: 19},
    { id: 35, application_form_id: 2, conditions_support_id: 19},
    { id: 36, application_form_id: 1, conditions_support_id: 20},
    { id: 37, application_form_id: 3, conditions_support_id: 20},
    { id: 38, application_form_id: 1, conditions_support_id: 21},
    { id: 39, application_form_id: 2, conditions_support_id: 21},
    { id: 40, application_form_id: 3, conditions_support_id: 21},
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第三子
    { id: 41, application_form_id: 1, conditions_support_id: 22},
    { id: 42, application_form_id: 1, conditions_support_id: 23},
    { id: 43, application_form_id: 2, conditions_support_id: 23},
    { id: 44, application_form_id: 1, conditions_support_id: 24},
    { id: 45, application_form_id: 3, conditions_support_id: 24},
    { id: 46, application_form_id: 1, conditions_support_id: 25},
    { id: 47, application_form_id: 2, conditions_support_id: 25},
    { id: 48, application_form_id: 3, conditions_support_id: 25},
    ##私立幼稚園等保護者補助金-360万未満-第一子
    { id: 49, application_form_id: 1, conditions_support_id: 26},
    { id: 50, application_form_id: 1, conditions_support_id: 27},
    { id: 51, application_form_id: 2, conditions_support_id: 27},
    { id: 52, application_form_id: 1, conditions_support_id: 28},
    { id: 53, application_form_id: 3, conditions_support_id: 28},
    { id: 54, application_form_id: 1, conditions_support_id: 29},
    { id: 55, application_form_id: 2, conditions_support_id: 29},
    { id: 56, application_form_id: 3, conditions_support_id: 29},
    ##私立幼稚園等保護者補助金-360万未満-第二子
    { id: 57, application_form_id: 1, conditions_support_id: 30},
    { id: 58, application_form_id: 1, conditions_support_id: 31},
    { id: 59, application_form_id: 2, conditions_support_id: 31},
    { id: 60, application_form_id: 1, conditions_support_id: 32},
    { id: 61, application_form_id: 3, conditions_support_id: 32},
    { id: 62, application_form_id: 1, conditions_support_id: 33},
    { id: 63, application_form_id: 2, conditions_support_id: 33},
    { id: 64, application_form_id: 3, conditions_support_id: 33},
    ##私立幼稚園等保護者補助金-360万未満-第三子
    { id: 65, application_form_id: 1, conditions_support_id: 34},
    { id: 66, application_form_id: 1, conditions_support_id: 35},
    { id: 67, application_form_id: 2, conditions_support_id: 35},
    { id: 68, application_form_id: 1, conditions_support_id: 36},
    { id: 69, application_form_id: 3, conditions_support_id: 36},
    { id: 70, application_form_id: 1, conditions_support_id: 37},
    { id: 71, application_form_id: 2, conditions_support_id: 37},
    { id: 72, application_form_id: 3, conditions_support_id: 37},
    ##私立幼稚園等保護者補助金-680万未満-第一子
    { id: 73, application_form_id: 1, conditions_support_id: 38},
    { id: 74, application_form_id: 1, conditions_support_id: 39},
    { id: 75, application_form_id: 2, conditions_support_id: 39},
    { id: 76, application_form_id: 1, conditions_support_id: 40},
    { id: 77, application_form_id: 3, conditions_support_id: 40},
    { id: 78, application_form_id: 1, conditions_support_id: 41},
    { id: 79, application_form_id: 2, conditions_support_id: 41},
    { id: 80, application_form_id: 3, conditions_support_id: 41},
    ##私立幼稚園等保護者補助金-680万未満-第二子
    { id: 81, application_form_id: 1, conditions_support_id: 42},
    { id: 82, application_form_id: 1, conditions_support_id: 43},
    { id: 83, application_form_id: 2, conditions_support_id: 43},
    { id: 84, application_form_id: 1, conditions_support_id: 44},
    { id: 85, application_form_id: 3, conditions_support_id: 44},
    { id: 86, application_form_id: 1, conditions_support_id: 45},
    { id: 87, application_form_id: 2, conditions_support_id: 45},
    { id: 88, application_form_id: 3, conditions_support_id: 45},
    ##私立幼稚園等保護者補助金-680万未満-第三子
    { id: 89, application_form_id: 1, conditions_support_id: 46},
    { id: 90, application_form_id: 1, conditions_support_id: 47},
    { id: 91, application_form_id: 2, conditions_support_id: 47},
    { id: 92, application_form_id: 1, conditions_support_id: 48},
    { id: 93, application_form_id: 3, conditions_support_id: 48},
    { id: 94, application_form_id: 1, conditions_support_id: 49},
    { id: 95, application_form_id: 2, conditions_support_id: 49},
    { id: 96, application_form_id: 3, conditions_support_id: 49},
    ##私立幼稚園等保護者補助金-730万未満-第一子
    { id: 97, application_form_id: 1, conditions_support_id: 50},
    { id: 98, application_form_id: 1, conditions_support_id: 51},
    { id: 99, application_form_id: 2, conditions_support_id: 51},
    { id: 100, application_form_id: 1, conditions_support_id: 52},
    { id: 101, application_form_id: 3, conditions_support_id: 52},
    { id: 102, application_form_id: 1, conditions_support_id: 53},
    { id: 103, application_form_id: 2, conditions_support_id: 53},
    { id: 104, application_form_id: 3, conditions_support_id: 53},
    ##私立幼稚園等保護者補助金-730万未満-第二子
    { id: 105, application_form_id: 1, conditions_support_id: 54},
    { id: 106, application_form_id: 1, conditions_support_id: 55},
    { id: 107, application_form_id: 2, conditions_support_id: 55},
    { id: 108, application_form_id: 1, conditions_support_id: 56},
    { id: 109, application_form_id: 3, conditions_support_id: 56},
    { id: 110, application_form_id: 1, conditions_support_id: 57},
    { id: 111, application_form_id: 2, conditions_support_id: 57},
    { id: 112, application_form_id: 3, conditions_support_id: 57},
    ##私立幼稚園等保護者補助金-730万未満-第三子
    { id: 113, application_form_id: 1, conditions_support_id: 58},
    { id: 114, application_form_id: 1, conditions_support_id: 59},
    { id: 115, application_form_id: 2, conditions_support_id: 59},
    { id: 116, application_form_id: 1, conditions_support_id: 60},
    { id: 117, application_form_id: 3, conditions_support_id: 60},
    { id: 118, application_form_id: 1, conditions_support_id: 61},
    { id: 119, application_form_id: 2, conditions_support_id: 61},
    { id: 120, application_form_id: 3, conditions_support_id: 61},
    ##私立幼稚園等保護者補助金-730万以上-第一子
    { id: 121, application_form_id: 1, conditions_support_id: 62},
    { id: 122, application_form_id: 1, conditions_support_id: 63},
    { id: 123, application_form_id: 2, conditions_support_id: 63},
    { id: 124, application_form_id: 1, conditions_support_id: 64},
    { id: 125, application_form_id: 3, conditions_support_id: 64},
    { id: 126, application_form_id: 1, conditions_support_id: 65},
    { id: 127, application_form_id: 2, conditions_support_id: 65},
    { id: 128, application_form_id: 3, conditions_support_id: 65},
    ##私立幼稚園等保護者補助金-730万以上-第二子
    { id: 129, application_form_id: 1, conditions_support_id: 66},
    { id: 130, application_form_id: 1, conditions_support_id: 67},
    { id: 131, application_form_id: 2, conditions_support_id: 67},
    { id: 132, application_form_id: 1, conditions_support_id: 68},
    { id: 133, application_form_id: 3, conditions_support_id: 68},
    { id: 134, application_form_id: 1, conditions_support_id: 69},
    { id: 135, application_form_id: 2, conditions_support_id: 69},
    { id: 136, application_form_id: 3, conditions_support_id: 69},
    ##私立幼稚園等保護者補助金-730万以上-第三子
    { id: 137, application_form_id: 1, conditions_support_id: 70},
    { id: 138, application_form_id: 1, conditions_support_id: 71},
    { id: 139, application_form_id: 2, conditions_support_id: 71},
    { id: 140, application_form_id: 1, conditions_support_id: 72},
    { id: 141, application_form_id: 3, conditions_support_id: 72},
    { id: 142, application_form_id: 1, conditions_support_id: 73},
    { id: 143, application_form_id: 2, conditions_support_id: 73},
    { id: 144, application_form_id: 3, conditions_support_id: 73},
    ## 入園料金補助金（私立幼稚園)
    { id: 145, application_form_id: 4, conditions_support_id: 1},
  ]
)
