ConditionsSupportsAddinfoApplication.create!(
  [
    ##私立幼稚園等保護者補助金-生活保護-第一子
    { id: 1, addinfo_application_id: 1, conditions_support_id: 2 },
    { id: 2, addinfo_application_id: 2, conditions_support_id: 2 },
    { id: 3, addinfo_application_id: 1, conditions_support_id: 3 },
    { id: 4, addinfo_application_id: 2, conditions_support_id: 3 },
    { id: 5, addinfo_application_id: 3, conditions_support_id: 3 },
    { id: 6, addinfo_application_id: 4, conditions_support_id: 3 },
    { id: 7, addinfo_application_id: 5, conditions_support_id: 3 },
    { id: 8, addinfo_application_id: 1, conditions_support_id: 4 },
    { id: 9, addinfo_application_id: 2, conditions_support_id: 4 },
    { id: 10, addinfo_application_id: 3, conditions_support_id: 4 },
    { id: 11, addinfo_application_id: 4, conditions_support_id: 4 },
    { id: 12, addinfo_application_id: 5, conditions_support_id: 4 },
    { id: 13, addinfo_application_id: 1, conditions_support_id: 5 },
    { id: 14, addinfo_application_id: 2, conditions_support_id: 5 },
    { id: 15, addinfo_application_id: 3, conditions_support_id: 5 },
    { id: 16, addinfo_application_id: 4, conditions_support_id: 5 },
    { id: 17, addinfo_application_id: 5, conditions_support_id: 5 },
    ##私立幼稚園等保護者補助金-生活保護-第二子
    { id: 18, addinfo_application_id: 1, conditions_support_id: 6 },
    { id: 19, addinfo_application_id: 2, conditions_support_id: 6 },
    { id: 20, addinfo_application_id: 1, conditions_support_id: 7 },
    { id: 21, addinfo_application_id: 2, conditions_support_id: 7 },
    { id: 22, addinfo_application_id: 3, conditions_support_id: 7 },
    { id: 23, addinfo_application_id: 4, conditions_support_id: 7 },
    { id: 24, addinfo_application_id: 5, conditions_support_id: 7 },
    { id: 25, addinfo_application_id: 1, conditions_support_id: 8 },
    { id: 26, addinfo_application_id: 2, conditions_support_id: 8 },
    { id: 27, addinfo_application_id: 3, conditions_support_id: 8 },
    { id: 28, addinfo_application_id: 4, conditions_support_id: 8 },
    { id: 29, addinfo_application_id: 5, conditions_support_id: 8 },
    { id: 30, addinfo_application_id: 1, conditions_support_id: 9 },
    { id: 31, addinfo_application_id: 2, conditions_support_id: 9 },
    { id: 32, addinfo_application_id: 3, conditions_support_id: 9 },
    { id: 33, addinfo_application_id: 4, conditions_support_id: 9 },
    { id: 34, addinfo_application_id: 5, conditions_support_id: 9 },
    ##私立幼稚園等保護者補助金-生活保護-第三子
    { id: 35, addinfo_application_id: 1, conditions_support_id: 10 },
    { id: 36, addinfo_application_id: 2, conditions_support_id: 10 },
    { id: 37, addinfo_application_id: 1, conditions_support_id: 11 },
    { id: 38, addinfo_application_id: 2, conditions_support_id: 11 },
    { id: 39, addinfo_application_id: 3, conditions_support_id: 11 },
    { id: 40, addinfo_application_id: 4, conditions_support_id: 11 },
    { id: 41, addinfo_application_id: 5, conditions_support_id: 11 },
    { id: 42, addinfo_application_id: 1, conditions_support_id: 12 },
    { id: 43, addinfo_application_id: 2, conditions_support_id: 12 },
    { id: 44, addinfo_application_id: 3, conditions_support_id: 12 },
    { id: 45, addinfo_application_id: 4, conditions_support_id: 12 },
    { id: 46, addinfo_application_id: 5, conditions_support_id: 12 },
    { id: 47, addinfo_application_id: 1, conditions_support_id: 13 },
    { id: 48, addinfo_application_id: 2, conditions_support_id: 13 },
    { id: 49, addinfo_application_id: 3, conditions_support_id: 13 },
    { id: 50, addinfo_application_id: 4, conditions_support_id: 13 },
    { id: 51, addinfo_application_id: 5, conditions_support_id: 13 },
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第一子
    { id: 52, addinfo_application_id: 2, conditions_support_id: 14 },
    { id: 53, addinfo_application_id: 2, conditions_support_id: 15 },
    { id: 54, addinfo_application_id: 3, conditions_support_id: 15 },
    { id: 55, addinfo_application_id: 4, conditions_support_id: 15 },
    { id: 56, addinfo_application_id: 5, conditions_support_id: 15 },
    { id: 57, addinfo_application_id: 2, conditions_support_id: 16 },
    { id: 58, addinfo_application_id: 3, conditions_support_id: 16 },
    { id: 59, addinfo_application_id: 4, conditions_support_id: 16 },
    { id: 60, addinfo_application_id: 5, conditions_support_id: 16 },
    { id: 61, addinfo_application_id: 2, conditions_support_id: 17 },
    { id: 62, addinfo_application_id: 3, conditions_support_id: 17 },
    { id: 63, addinfo_application_id: 4, conditions_support_id: 17 },
    { id: 64, addinfo_application_id: 5, conditions_support_id: 17 },
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第二子
    { id: 65, addinfo_application_id: 2, conditions_support_id: 18 },
    { id: 66, addinfo_application_id: 2, conditions_support_id: 19 },
    { id: 67, addinfo_application_id: 3, conditions_support_id: 19 },
    { id: 68, addinfo_application_id: 4, conditions_support_id: 19 },
    { id: 69, addinfo_application_id: 5, conditions_support_id: 19 },
    { id: 70, addinfo_application_id: 2, conditions_support_id: 20 },
    { id: 71, addinfo_application_id: 3, conditions_support_id: 20 },
    { id: 72, addinfo_application_id: 4, conditions_support_id: 20 },
    { id: 73, addinfo_application_id: 5, conditions_support_id: 20 },
    { id: 74, addinfo_application_id: 2, conditions_support_id: 21 },
    { id: 75, addinfo_application_id: 3, conditions_support_id: 21 },
    { id: 76, addinfo_application_id: 4, conditions_support_id: 21 },
    { id: 77, addinfo_application_id: 5, conditions_support_id: 21 },
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第三子
    { id: 78, addinfo_application_id: 2, conditions_support_id: 22 },
    { id: 79, addinfo_application_id: 2, conditions_support_id: 23 },
    { id: 80, addinfo_application_id: 3, conditions_support_id: 23 },
    { id: 81, addinfo_application_id: 4, conditions_support_id: 23 },
    { id: 82, addinfo_application_id: 5, conditions_support_id: 23 },
    { id: 83, addinfo_application_id: 2, conditions_support_id: 24 },
    { id: 84, addinfo_application_id: 3, conditions_support_id: 24 },
    { id: 85, addinfo_application_id: 4, conditions_support_id: 24 },
    { id: 86, addinfo_application_id: 5, conditions_support_id: 24 },
    { id: 87, addinfo_application_id: 2, conditions_support_id: 25 },
    { id: 88, addinfo_application_id: 3, conditions_support_id: 25 },
    { id: 89, addinfo_application_id: 4, conditions_support_id: 25 },
    { id: 90, addinfo_application_id: 5, conditions_support_id: 25 },
    ##私立幼稚園等保護者補助金-360万未満-第一子
    { id: 91, addinfo_application_id: 2, conditions_support_id: 26 },
    { id: 92, addinfo_application_id: 2, conditions_support_id: 27 },
    { id: 93, addinfo_application_id: 3, conditions_support_id: 27 },
    { id: 94, addinfo_application_id: 4, conditions_support_id: 27 },
    { id: 95, addinfo_application_id: 5, conditions_support_id: 27 },
    { id: 96, addinfo_application_id: 2, conditions_support_id: 28 },
    { id: 97, addinfo_application_id: 3, conditions_support_id: 28 },
    { id: 98, addinfo_application_id: 4, conditions_support_id: 28 },
    { id: 99, addinfo_application_id: 5, conditions_support_id: 28 },
    { id: 100, addinfo_application_id: 2, conditions_support_id: 29 },
    { id: 101, addinfo_application_id: 3, conditions_support_id: 29 },
    { id: 102, addinfo_application_id: 4, conditions_support_id: 29 },
    { id: 103, addinfo_application_id: 5, conditions_support_id: 29 },
    ##私立幼稚園等保護者補助金-360万未満-第二子
    { id: 104, addinfo_application_id: 2, conditions_support_id: 30 },
    { id: 105, addinfo_application_id: 2, conditions_support_id: 31 },
    { id: 106, addinfo_application_id: 3, conditions_support_id: 31 },
    { id: 107, addinfo_application_id: 4, conditions_support_id: 31 },
    { id: 108, addinfo_application_id: 5, conditions_support_id: 31 },
    { id: 109, addinfo_application_id: 2, conditions_support_id: 32 },
    { id: 110, addinfo_application_id: 3, conditions_support_id: 32 },
    { id: 111, addinfo_application_id: 4, conditions_support_id: 32 },
    { id: 112, addinfo_application_id: 5, conditions_support_id: 32 },
    { id: 113, addinfo_application_id: 2, conditions_support_id: 33 },
    { id: 114, addinfo_application_id: 3, conditions_support_id: 33 },
    { id: 115, addinfo_application_id: 4, conditions_support_id: 33 },
    { id: 116, addinfo_application_id: 5, conditions_support_id: 33 },
    ##私立幼稚園等保護者補助金-360万未満-第三子
    { id: 117, addinfo_application_id: 2, conditions_support_id: 34 },
    { id: 118, addinfo_application_id: 2, conditions_support_id: 35 },
    { id: 119, addinfo_application_id: 3, conditions_support_id: 35},
    { id: 120, addinfo_application_id: 4, conditions_support_id: 35 },
    { id: 121, addinfo_application_id: 5, conditions_support_id: 35 },
    { id: 122, addinfo_application_id: 2, conditions_support_id: 36 },
    { id: 123, addinfo_application_id: 3, conditions_support_id: 36 },
    { id: 124, addinfo_application_id: 4, conditions_support_id: 36 },
    { id: 125, addinfo_application_id: 5, conditions_support_id: 36 },
    { id: 126, addinfo_application_id: 2, conditions_support_id: 37 },
    { id: 127, addinfo_application_id: 3, conditions_support_id: 37 },
    { id: 128, addinfo_application_id: 4, conditions_support_id: 37 },
    { id: 129, addinfo_application_id: 5, conditions_support_id: 37 },
    ##私立幼稚園等保護者補助金-680万未満-第一子
    { id: 130, addinfo_application_id: 3, conditions_support_id: 39 },
    { id: 131, addinfo_application_id: 4, conditions_support_id: 39 },
    { id: 132, addinfo_application_id: 5, conditions_support_id: 39 },
    { id: 133, addinfo_application_id: 3, conditions_support_id: 40 },
    { id: 134, addinfo_application_id: 4, conditions_support_id: 40 },
    { id: 135, addinfo_application_id: 5, conditions_support_id: 40 },
    { id: 136, addinfo_application_id: 3, conditions_support_id: 41 },
    { id: 137, addinfo_application_id: 4, conditions_support_id: 41 },
    { id: 138, addinfo_application_id: 5, conditions_support_id: 41 },
    ##私立幼稚園等保護者補助金-680万未満-第二子
    { id: 139, addinfo_application_id: 3, conditions_support_id: 43 },
    { id: 140, addinfo_application_id: 4, conditions_support_id: 43 },
    { id: 141, addinfo_application_id: 5, conditions_support_id: 43 },
    { id: 142, addinfo_application_id: 3, conditions_support_id: 44 },
    { id: 143, addinfo_application_id: 4, conditions_support_id: 44 },
    { id: 144, addinfo_application_id: 5, conditions_support_id: 44 },
    { id: 145, addinfo_application_id: 3, conditions_support_id: 45 },
    { id: 146, addinfo_application_id: 4, conditions_support_id: 45 },
    { id: 147, addinfo_application_id: 5, conditions_support_id: 45 },
    ##私立幼稚園等保護者補助金-680万未満-第三子
    { id: 148, addinfo_application_id: 3, conditions_support_id: 47 },
    { id: 149, addinfo_application_id: 4, conditions_support_id: 47 },
    { id: 150, addinfo_application_id: 5, conditions_support_id: 47 },
    { id: 151, addinfo_application_id: 3, conditions_support_id: 48 },
    { id: 152, addinfo_application_id: 4, conditions_support_id: 48 },
    { id: 153, addinfo_application_id: 5, conditions_support_id: 48 },
    { id: 154, addinfo_application_id: 3, conditions_support_id: 49 },
    { id: 155, addinfo_application_id: 4, conditions_support_id: 49 },
    { id: 156, addinfo_application_id: 5, conditions_support_id: 49 },
    ##私立幼稚園等保護者補助金-730万未満-第一子
    { id: 157, addinfo_application_id: 3, conditions_support_id: 51 },
    { id: 158, addinfo_application_id: 4, conditions_support_id: 51 },
    { id: 159, addinfo_application_id: 5, conditions_support_id: 51 },
    { id: 160, addinfo_application_id: 3, conditions_support_id: 52 },
    { id: 161, addinfo_application_id: 4, conditions_support_id: 52 },
    { id: 162, addinfo_application_id: 5, conditions_support_id: 52 },
    { id: 163, addinfo_application_id: 3, conditions_support_id: 53 },
    { id: 164, addinfo_application_id: 4, conditions_support_id: 53 },
    { id: 165, addinfo_application_id: 5, conditions_support_id: 53 },
    ##私立幼稚園等保護者補助金-730万未満-第二子
    { id: 166, addinfo_application_id: 3, conditions_support_id: 55 },
    { id: 167, addinfo_application_id: 4, conditions_support_id: 55 },
    { id: 168, addinfo_application_id: 5, conditions_support_id: 55 },
    { id: 169, addinfo_application_id: 3, conditions_support_id: 56 },
    { id: 170, addinfo_application_id: 4, conditions_support_id: 56 },
    { id: 171, addinfo_application_id: 5, conditions_support_id: 56 },
    { id: 172, addinfo_application_id: 3, conditions_support_id: 57 },
    { id: 173, addinfo_application_id: 4, conditions_support_id: 57 },
    { id: 174, addinfo_application_id: 5, conditions_support_id: 57 },
    ##私立幼稚園等保護者補助金-730万未満-第三子
    { id: 175, addinfo_application_id: 3, conditions_support_id: 59 },
    { id: 176, addinfo_application_id: 4, conditions_support_id: 59 },
    { id: 177, addinfo_application_id: 5, conditions_support_id: 59 },
    { id: 178, addinfo_application_id: 3, conditions_support_id: 60 },
    { id: 179, addinfo_application_id: 4, conditions_support_id: 60 },
    { id: 180, addinfo_application_id: 5, conditions_support_id: 60 },
    { id: 181, addinfo_application_id: 3, conditions_support_id: 61 },
    { id: 182, addinfo_application_id: 4, conditions_support_id: 61 },
    { id: 188, addinfo_application_id: 5, conditions_support_id: 61 },
    ##私立幼稚園等保護者補助金-730万以上-第一子
    { id: 189, addinfo_application_id: 3, conditions_support_id: 63 },
    { id: 190, addinfo_application_id: 4, conditions_support_id: 63 },
    { id: 191, addinfo_application_id: 5, conditions_support_id: 63 },
    { id: 192, addinfo_application_id: 3, conditions_support_id: 64 },
    { id: 193, addinfo_application_id: 4, conditions_support_id: 64 },
    { id: 194, addinfo_application_id: 5, conditions_support_id: 64 },
    { id: 195, addinfo_application_id: 3, conditions_support_id: 65 },
    { id: 196, addinfo_application_id: 4, conditions_support_id: 65 },
    { id: 197, addinfo_application_id: 5, conditions_support_id: 65 },
    ##私立幼稚園等保護者補助金-730万以上-第二子
    { id: 198, addinfo_application_id: 3, conditions_support_id: 67 },
    { id: 199, addinfo_application_id: 4, conditions_support_id: 67 },
    { id: 200, addinfo_application_id: 5, conditions_support_id: 67 },
    { id: 201, addinfo_application_id: 3, conditions_support_id: 68 },
    { id: 202, addinfo_application_id: 4, conditions_support_id: 68 },
    { id: 203, addinfo_application_id: 5, conditions_support_id: 68 },
    { id: 204, addinfo_application_id: 3, conditions_support_id: 69 },
    { id: 205, addinfo_application_id: 4, conditions_support_id: 69 },
    { id: 206, addinfo_application_id: 5, conditions_support_id: 69 },
    ##私立幼稚園等保護者補助金-730万以上-第三子
    { id: 207, addinfo_application_id: 3, conditions_support_id: 71 },
    { id: 208, addinfo_application_id: 4, conditions_support_id: 71 },
    { id: 209, addinfo_application_id: 5, conditions_support_id: 71 },
    { id: 210, addinfo_application_id: 3, conditions_support_id: 72 },
    { id: 211, addinfo_application_id: 4, conditions_support_id: 72 },
    { id: 212, addinfo_application_id: 5, conditions_support_id: 72 },
    { id: 213, addinfo_application_id: 3, conditions_support_id: 73 },
    { id: 214, addinfo_application_id: 4, conditions_support_id: 73 },
    { id: 215, addinfo_application_id: 5, conditions_support_id: 73 },
  ]
)
