ConditionsSupportsAddinfoApplication.create!(
  [
    ##私立幼稚園等保護者補助金-生活保護-第一子
    { id: 1, additional_info_of_application_id: 1, conditions_support_id: 2 },
    { id: 2, additional_info_of_application_id: 2, conditions_support_id: 2 },
    { id: 3, additional_info_of_application_id: 1, conditions_support_id: 3 },
    { id: 4, additional_info_of_application_id: 2, conditions_support_id: 3 },
    { id: 5, additional_info_of_application_id: 3, conditions_support_id: 3 },
    { id: 6, additional_info_of_application_id: 4, conditions_support_id: 3 },
    { id: 7, additional_info_of_application_id: 5, conditions_support_id: 3 },
    { id: 8, additional_info_of_application_id: 1, conditions_support_id: 4 },
    { id: 9, additional_info_of_application_id: 2, conditions_support_id: 4 },
    { id: 10, additional_info_of_application_id: 3, conditions_support_id: 4 },
    { id: 11, additional_info_of_application_id: 4, conditions_support_id: 4 },
    { id: 12, additional_info_of_application_id: 5, conditions_support_id: 4 },
    { id: 13, additional_info_of_application_id: 1, conditions_support_id: 5 },
    { id: 14, additional_info_of_application_id: 2, conditions_support_id: 5 },
    { id: 15, additional_info_of_application_id: 3, conditions_support_id: 5 },
    { id: 16, additional_info_of_application_id: 4, conditions_support_id: 5 },
    { id: 17, additional_info_of_application_id: 5, conditions_support_id: 5 },
    ##私立幼稚園等保護者補助金-生活保護-第二子
    { id: 18, additional_info_of_application_id: 1, conditions_support_id: 6 },
    { id: 19, additional_info_of_application_id: 2, conditions_support_id: 6 },
    { id: 20, additional_info_of_application_id: 1, conditions_support_id: 7 },
    { id: 21, additional_info_of_application_id: 2, conditions_support_id: 7 },
    { id: 22, additional_info_of_application_id: 3, conditions_support_id: 7 },
    { id: 23, additional_info_of_application_id: 4, conditions_support_id: 7 },
    { id: 24, additional_info_of_application_id: 5, conditions_support_id: 7 },
    { id: 25, additional_info_of_application_id: 1, conditions_support_id: 8 },
    { id: 26, additional_info_of_application_id: 2, conditions_support_id: 8 },
    { id: 27, additional_info_of_application_id: 3, conditions_support_id: 8 },
    { id: 28, additional_info_of_application_id: 4, conditions_support_id: 8 },
    { id: 29, additional_info_of_application_id: 5, conditions_support_id: 8 },
    { id: 30, additional_info_of_application_id: 1, conditions_support_id: 9 },
    { id: 31, additional_info_of_application_id: 2, conditions_support_id: 9 },
    { id: 32, additional_info_of_application_id: 3, conditions_support_id: 9 },
    { id: 33, additional_info_of_application_id: 4, conditions_support_id: 9 },
    { id: 34, additional_info_of_application_id: 5, conditions_support_id: 9 },
    ##私立幼稚園等保護者補助金-生活保護-第三子
    { id: 35, additional_info_of_application_id: 1, conditions_support_id: 10 },
    { id: 36, additional_info_of_application_id: 2, conditions_support_id: 10 },
    { id: 37, additional_info_of_application_id: 1, conditions_support_id: 11 },
    { id: 38, additional_info_of_application_id: 2, conditions_support_id: 11 },
    { id: 39, additional_info_of_application_id: 3, conditions_support_id: 11 },
    { id: 40, additional_info_of_application_id: 4, conditions_support_id: 11 },
    { id: 41, additional_info_of_application_id: 5, conditions_support_id: 11 },
    { id: 42, additional_info_of_application_id: 1, conditions_support_id: 12 },
    { id: 43, additional_info_of_application_id: 2, conditions_support_id: 12 },
    { id: 44, additional_info_of_application_id: 3, conditions_support_id: 12 },
    { id: 45, additional_info_of_application_id: 4, conditions_support_id: 12 },
    { id: 46, additional_info_of_application_id: 5, conditions_support_id: 12 },
    { id: 47, additional_info_of_application_id: 1, conditions_support_id: 13 },
    { id: 48, additional_info_of_application_id: 2, conditions_support_id: 13 },
    { id: 49, additional_info_of_application_id: 3, conditions_support_id: 13 },
    { id: 50, additional_info_of_application_id: 4, conditions_support_id: 13 },
    { id: 51, additional_info_of_application_id: 5, conditions_support_id: 13 },
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第一子
    { id: 52, additional_info_of_application_id: 2, conditions_support_id: 14 },
    { id: 53, additional_info_of_application_id: 2, conditions_support_id: 15 },
    { id: 54, additional_info_of_application_id: 3, conditions_support_id: 15 },
    { id: 55, additional_info_of_application_id: 4, conditions_support_id: 15 },
    { id: 56, additional_info_of_application_id: 5, conditions_support_id: 15 },
    { id: 57, additional_info_of_application_id: 2, conditions_support_id: 16 },
    { id: 58, additional_info_of_application_id: 3, conditions_support_id: 16 },
    { id: 59, additional_info_of_application_id: 4, conditions_support_id: 16 },
    { id: 60, additional_info_of_application_id: 5, conditions_support_id: 16 },
    { id: 61, additional_info_of_application_id: 2, conditions_support_id: 17 },
    { id: 62, additional_info_of_application_id: 3, conditions_support_id: 17 },
    { id: 63, additional_info_of_application_id: 4, conditions_support_id: 17 },
    { id: 64, additional_info_of_application_id: 5, conditions_support_id: 17 },
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第二子
    { id: 65, additional_info_of_application_id: 2, conditions_support_id: 18 },
    { id: 66, additional_info_of_application_id: 2, conditions_support_id: 19 },
    { id: 67, additional_info_of_application_id: 3, conditions_support_id: 19 },
    { id: 68, additional_info_of_application_id: 4, conditions_support_id: 19 },
    { id: 69, additional_info_of_application_id: 5, conditions_support_id: 19 },
    { id: 70, additional_info_of_application_id: 2, conditions_support_id: 20 },
    { id: 71, additional_info_of_application_id: 3, conditions_support_id: 20 },
    { id: 72, additional_info_of_application_id: 4, conditions_support_id: 20 },
    { id: 73, additional_info_of_application_id: 5, conditions_support_id: 20 },
    { id: 74, additional_info_of_application_id: 2, conditions_support_id: 21 },
    { id: 75, additional_info_of_application_id: 3, conditions_support_id: 21 },
    { id: 76, additional_info_of_application_id: 4, conditions_support_id: 21 },
    { id: 77, additional_info_of_application_id: 5, conditions_support_id: 21 },
    ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税-第三子
    { id: 78, additional_info_of_application_id: 2, conditions_support_id: 22 },
    { id: 79, additional_info_of_application_id: 2, conditions_support_id: 23 },
    { id: 80, additional_info_of_application_id: 3, conditions_support_id: 23 },
    { id: 81, additional_info_of_application_id: 4, conditions_support_id: 23 },
    { id: 82, additional_info_of_application_id: 5, conditions_support_id: 23 },
    { id: 83, additional_info_of_application_id: 2, conditions_support_id: 24 },
    { id: 84, additional_info_of_application_id: 3, conditions_support_id: 24 },
    { id: 85, additional_info_of_application_id: 4, conditions_support_id: 24 },
    { id: 86, additional_info_of_application_id: 5, conditions_support_id: 24 },
    { id: 87, additional_info_of_application_id: 2, conditions_support_id: 25 },
    { id: 88, additional_info_of_application_id: 3, conditions_support_id: 25 },
    { id: 89, additional_info_of_application_id: 4, conditions_support_id: 25 },
    { id: 90, additional_info_of_application_id: 5, conditions_support_id: 25 },
    ##私立幼稚園等保護者補助金-360万未満-第一子
    { id: 91, additional_info_of_application_id: 2, conditions_support_id: 26 },
    { id: 92, additional_info_of_application_id: 2, conditions_support_id: 27 },
    { id: 93, additional_info_of_application_id: 3, conditions_support_id: 27 },
    { id: 94, additional_info_of_application_id: 4, conditions_support_id: 27 },
    { id: 95, additional_info_of_application_id: 5, conditions_support_id: 27 },
    { id: 96, additional_info_of_application_id: 2, conditions_support_id: 28 },
    { id: 97, additional_info_of_application_id: 3, conditions_support_id: 28 },
    { id: 98, additional_info_of_application_id: 4, conditions_support_id: 28 },
    { id: 99, additional_info_of_application_id: 5, conditions_support_id: 28 },
    { id: 100, additional_info_of_application_id: 2, conditions_support_id: 29 },
    { id: 101, additional_info_of_application_id: 3, conditions_support_id: 29 },
    { id: 102, additional_info_of_application_id: 4, conditions_support_id: 29 },
    { id: 103, additional_info_of_application_id: 5, conditions_support_id: 29 },
    ##私立幼稚園等保護者補助金-360万未満-第二子
    { id: 104, additional_info_of_application_id: 2, conditions_support_id: 30 },
    { id: 105, additional_info_of_application_id: 2, conditions_support_id: 31 },
    { id: 106, additional_info_of_application_id: 3, conditions_support_id: 31 },
    { id: 107, additional_info_of_application_id: 4, conditions_support_id: 31 },
    { id: 108, additional_info_of_application_id: 5, conditions_support_id: 31 },
    { id: 109, additional_info_of_application_id: 2, conditions_support_id: 32 },
    { id: 110, additional_info_of_application_id: 3, conditions_support_id: 32 },
    { id: 111, additional_info_of_application_id: 4, conditions_support_id: 32 },
    { id: 112, additional_info_of_application_id: 5, conditions_support_id: 32 },
    { id: 113, additional_info_of_application_id: 2, conditions_support_id: 33 },
    { id: 114, additional_info_of_application_id: 3, conditions_support_id: 33 },
    { id: 115, additional_info_of_application_id: 4, conditions_support_id: 33 },
    { id: 116, additional_info_of_application_id: 5, conditions_support_id: 33 },
    ##私立幼稚園等保護者補助金-360万未満-第三子
    { id: 117, additional_info_of_application_id: 2, conditions_support_id: 34 },
    { id: 118, additional_info_of_application_id: 2, conditions_support_id: 35 },
    { id: 119, additional_info_of_application_id: 3, conditions_support_id: 35},
    { id: 120, additional_info_of_application_id: 4, conditions_support_id: 35 },
    { id: 121, additional_info_of_application_id: 5, conditions_support_id: 35 },
    { id: 122, additional_info_of_application_id: 2, conditions_support_id: 36 },
    { id: 123, additional_info_of_application_id: 3, conditions_support_id: 36 },
    { id: 124, additional_info_of_application_id: 4, conditions_support_id: 36 },
    { id: 125, additional_info_of_application_id: 5, conditions_support_id: 36 },
    { id: 126, additional_info_of_application_id: 2, conditions_support_id: 37 },
    { id: 127, additional_info_of_application_id: 3, conditions_support_id: 37 },
    { id: 128, additional_info_of_application_id: 4, conditions_support_id: 37 },
    { id: 129, additional_info_of_application_id: 5, conditions_support_id: 37 },
    ##私立幼稚園等保護者補助金-680万未満-第一子
    { id: 130, additional_info_of_application_id: 3, conditions_support_id: 39 },
    { id: 131, additional_info_of_application_id: 4, conditions_support_id: 39 },
    { id: 132, additional_info_of_application_id: 5, conditions_support_id: 39 },
    { id: 133, additional_info_of_application_id: 3, conditions_support_id: 40 },
    { id: 134, additional_info_of_application_id: 4, conditions_support_id: 40 },
    { id: 135, additional_info_of_application_id: 5, conditions_support_id: 40 },
    { id: 136, additional_info_of_application_id: 3, conditions_support_id: 41 },
    { id: 137, additional_info_of_application_id: 4, conditions_support_id: 41 },
    { id: 138, additional_info_of_application_id: 5, conditions_support_id: 41 },
    ##私立幼稚園等保護者補助金-680万未満-第二子
    { id: 139, additional_info_of_application_id: 3, conditions_support_id: 43 },
    { id: 140, additional_info_of_application_id: 4, conditions_support_id: 43 },
    { id: 141, additional_info_of_application_id: 5, conditions_support_id: 43 },
    { id: 142, additional_info_of_application_id: 3, conditions_support_id: 44 },
    { id: 143, additional_info_of_application_id: 4, conditions_support_id: 44 },
    { id: 144, additional_info_of_application_id: 5, conditions_support_id: 44 },
    { id: 145, additional_info_of_application_id: 3, conditions_support_id: 45 },
    { id: 146, additional_info_of_application_id: 4, conditions_support_id: 45 },
    { id: 147, additional_info_of_application_id: 5, conditions_support_id: 45 },
    ##私立幼稚園等保護者補助金-680万未満-第三子
    { id: 148, additional_info_of_application_id: 3, conditions_support_id: 47 },
    { id: 149, additional_info_of_application_id: 4, conditions_support_id: 47 },
    { id: 150, additional_info_of_application_id: 5, conditions_support_id: 47 },
    { id: 151, additional_info_of_application_id: 3, conditions_support_id: 48 },
    { id: 152, additional_info_of_application_id: 4, conditions_support_id: 48 },
    { id: 153, additional_info_of_application_id: 5, conditions_support_id: 48 },
    { id: 154, additional_info_of_application_id: 3, conditions_support_id: 49 },
    { id: 155, additional_info_of_application_id: 4, conditions_support_id: 49 },
    { id: 156, additional_info_of_application_id: 5, conditions_support_id: 49 },
    ##私立幼稚園等保護者補助金-730万未満-第一子
    { id: 157, additional_info_of_application_id: 3, conditions_support_id: 51 },
    { id: 158, additional_info_of_application_id: 4, conditions_support_id: 51 },
    { id: 159, additional_info_of_application_id: 5, conditions_support_id: 51 },
    { id: 160, additional_info_of_application_id: 3, conditions_support_id: 52 },
    { id: 161, additional_info_of_application_id: 4, conditions_support_id: 52 },
    { id: 162, additional_info_of_application_id: 5, conditions_support_id: 52 },
    { id: 163, additional_info_of_application_id: 3, conditions_support_id: 53 },
    { id: 164, additional_info_of_application_id: 4, conditions_support_id: 53 },
    { id: 165, additional_info_of_application_id: 5, conditions_support_id: 53 },
    ##私立幼稚園等保護者補助金-730万未満-第二子
    { id: 166, additional_info_of_application_id: 3, conditions_support_id: 55 },
    { id: 167, additional_info_of_application_id: 4, conditions_support_id: 55 },
    { id: 168, additional_info_of_application_id: 5, conditions_support_id: 55 },
    { id: 169, additional_info_of_application_id: 3, conditions_support_id: 56 },
    { id: 170, additional_info_of_application_id: 4, conditions_support_id: 56 },
    { id: 171, additional_info_of_application_id: 5, conditions_support_id: 56 },
    { id: 172, additional_info_of_application_id: 3, conditions_support_id: 57 },
    { id: 173, additional_info_of_application_id: 4, conditions_support_id: 57 },
    { id: 174, additional_info_of_application_id: 5, conditions_support_id: 57 },
    ##私立幼稚園等保護者補助金-730万未満-第三子
    { id: 175, additional_info_of_application_id: 3, conditions_support_id: 59 },
    { id: 176, additional_info_of_application_id: 4, conditions_support_id: 59 },
    { id: 177, additional_info_of_application_id: 5, conditions_support_id: 59 },
    { id: 178, additional_info_of_application_id: 3, conditions_support_id: 60 },
    { id: 179, additional_info_of_application_id: 4, conditions_support_id: 60 },
    { id: 180, additional_info_of_application_id: 5, conditions_support_id: 60 },
    { id: 181, additional_info_of_application_id: 3, conditions_support_id: 61 },
    { id: 182, additional_info_of_application_id: 4, conditions_support_id: 61 },
    { id: 188, additional_info_of_application_id: 5, conditions_support_id: 61 },
    ##私立幼稚園等保護者補助金-730万以上-第一子
    { id: 189, additional_info_of_application_id: 3, conditions_support_id: 63 },
    { id: 190, additional_info_of_application_id: 4, conditions_support_id: 63 },
    { id: 191, additional_info_of_application_id: 5, conditions_support_id: 63 },
    { id: 192, additional_info_of_application_id: 3, conditions_support_id: 64 },
    { id: 193, additional_info_of_application_id: 4, conditions_support_id: 64 },
    { id: 194, additional_info_of_application_id: 5, conditions_support_id: 64 },
    { id: 195, additional_info_of_application_id: 3, conditions_support_id: 65 },
    { id: 196, additional_info_of_application_id: 4, conditions_support_id: 65 },
    { id: 197, additional_info_of_application_id: 5, conditions_support_id: 65 },
    ##私立幼稚園等保護者補助金-730万以上-第二子
    { id: 198, additional_info_of_application_id: 3, conditions_support_id: 67 },
    { id: 199, additional_info_of_application_id: 4, conditions_support_id: 67 },
    { id: 200, additional_info_of_application_id: 5, conditions_support_id: 67 },
    { id: 201, additional_info_of_application_id: 3, conditions_support_id: 68 },
    { id: 202, additional_info_of_application_id: 4, conditions_support_id: 68 },
    { id: 203, additional_info_of_application_id: 5, conditions_support_id: 68 },
    { id: 204, additional_info_of_application_id: 3, conditions_support_id: 69 },
    { id: 205, additional_info_of_application_id: 4, conditions_support_id: 69 },
    { id: 206, additional_info_of_application_id: 5, conditions_support_id: 69 },
    ##私立幼稚園等保護者補助金-730万以上-第三子
    { id: 207, additional_info_of_application_id: 3, conditions_support_id: 71 },
    { id: 208, additional_info_of_application_id: 4, conditions_support_id: 71 },
    { id: 209, additional_info_of_application_id: 5, conditions_support_id: 71 },
    { id: 210, additional_info_of_application_id: 3, conditions_support_id: 72 },
    { id: 211, additional_info_of_application_id: 4, conditions_support_id: 72 },
    { id: 212, additional_info_of_application_id: 5, conditions_support_id: 72 },
    { id: 213, additional_info_of_application_id: 3, conditions_support_id: 73 },
    { id: 214, additional_info_of_application_id: 4, conditions_support_id: 73 },
    { id: 215, additional_info_of_application_id: 5, conditions_support_id: 73 },
  ]
)
