ConditionsSupport.create!(
  [
    { support_id: 2, condition_id: 1,
      payment: '180000',
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      city_id: 7,
      income_id: 1,
      age_id: 3,
    },
    { support_id: 2, condition_id: 2,
      payment: '180000',
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      city_id: 7,
      income_id: 2,
      age_id: 3,
    },
    { support_id: 2, condition_id: 2,
      payment: '120000',
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      city_id: 7,
      income_id: 2,
      age_id: 4,
    },
    { support_id: 2, condition_id: 2,
      payment: '120000',
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      city_id: 7,
      income_id: 2,
      age_id: 5,
    },
    { support_id: 2, condition_id: 3,
      payment: '180000',
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      city_id: 7,
      income_id: 3,
      age_id: 3,
    },
    { support_id: 2, condition_id: 3,
      payment: '120000',
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      city_id: 7,
      income_id: 3,
      age_id: 4,
    },
    { support_id: 2, condition_id: 3,
      payment: '120000',
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      city_id: 7,
      income_id: 3,
      age_id: 5,
    },
    { support_id: 2, condition_id: 4,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: 4,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
    { support_id: , condition_id: ,
      payment: '',
      url: '',
      city_id: ,
      income_id: ,
      age_id: ,
    },
  ]
)
