ConditionsSupportsApplicationsMethod.create!(
  [
    ## 入園料金補助金（私立幼稚園)
    { id: 1, application_method_id: 1, conditions_support_id: 1},
  ##私立幼稚園等保護者補助金-生活保護
    { id: 2, application_method_id: 2, conditions_support_id: 2},
    { id: 3, application_method_id: 2, conditions_support_id: 3},
    { id: 4, application_method_id: 2, conditions_support_id: 4},
    { id: 5, application_method_id: 2, conditions_support_id: 5},
    { id: 6, application_method_id: 2, conditions_support_id: 6},
    { id: 7, application_method_id: 2, conditions_support_id: 7},
    { id: 8, application_method_id: 2, conditions_support_id: 8},
    { id: 9, application_method_id: 2, conditions_support_id: 9},
    { id: 10, application_method_id: 2, conditions_support_id: 10},
    { id: 11, application_method_id: 2, conditions_support_id: 11},
    { id: 12, application_method_id: 2, conditions_support_id: 12},
    { id: 13, application_method_id: 2, conditions_support_id: 13},

  ##私立幼稚園等保護者補助金-住民税非課税および住民税所得割非課税
    { id: 14, application_method_id: 2, conditions_support_id: 14},
    { id: 15, application_method_id: 2, conditions_support_id: 15},
    { id: 16, application_method_id: 2, conditions_support_id: 16},
    { id: 17, application_method_id: 2, conditions_support_id: 17},
    { id: 18, application_method_id: 2, conditions_support_id: 18},
    { id: 19, application_method_id: 2, conditions_support_id: 19},
    { id: 20, application_method_id: 2, conditions_support_id: 20},
    { id: 21, application_method_id: 2, conditions_support_id: 21},
    { id: 22, application_method_id: 2, conditions_support_id: 22},
    { id: 23, application_method_id: 2, conditions_support_id: 23},
    { id: 24, application_method_id: 2, conditions_support_id: 24},
    { id: 25, application_method_id: 2, conditions_support_id: 25},

  ##私立幼稚園等保護者補助金-360万未満
    { id: 26, application_method_id: 2, conditions_support_id: 26},
    { id: 27, application_method_id: 2, conditions_support_id: 27},
    { id: 28, application_method_id: 2, conditions_support_id: 28},
    { id: 29, application_method_id: 2, conditions_support_id: 29},
    { id: 30, application_method_id: 2, conditions_support_id: 30},
    { id: 31, application_method_id: 2, conditions_support_id: 31},
    { id: 32, application_method_id: 2, conditions_support_id: 32},
    { id: 33, application_method_id: 2, conditions_support_id: 33},
    { id: 34, application_method_id: 2, conditions_support_id: 34},
    { id: 35, application_method_id: 2, conditions_support_id: 35},
    { id: 36, application_method_id: 2, conditions_support_id: 36},
    { id: 37, application_method_id: 2, conditions_support_id: 37},

  ##私立幼稚園等保護者補助金-680万未満
    { id: 38, application_method_id: 2, conditions_support_id: 38},
    { id: 39, application_method_id: 2, conditions_support_id: 39},
    { id: 40, application_method_id: 2, conditions_support_id: 40},
    { id: 41, application_method_id: 2, conditions_support_id: 41},
    { id: 42, application_method_id: 2, conditions_support_id: 42},
    { id: 43, application_method_id: 2, conditions_support_id: 43},
    { id: 44, application_method_id: 2, conditions_support_id: 44},
    { id: 45, application_method_id: 2, conditions_support_id: 45},
    { id: 46, application_method_id: 2, conditions_support_id: 46},
    { id: 47, application_method_id: 2, conditions_support_id: 47},
    { id: 48, application_method_id: 2, conditions_support_id: 48},
    { id: 49, application_method_id: 2, conditions_support_id: 49},

  ##私立幼稚園等保護者補助金-730万未満
    { id: 50, application_method_id: 2, conditions_support_id: 50},
    { id: 51, application_method_id: 2, conditions_support_id: 51},
    { id: 52, application_method_id: 2, conditions_support_id: 52},
    { id: 53, application_method_id: 2, conditions_support_id: 53},
    { id: 54, application_method_id: 2, conditions_support_id: 54},
    { id: 55, application_method_id: 2, conditions_support_id: 55},
    { id: 56, application_method_id: 2, conditions_support_id: 56},
    { id: 57, application_method_id: 2, conditions_support_id: 57},
    { id: 58, application_method_id: 2, conditions_support_id: 58},
    { id: 59, application_method_id: 2, conditions_support_id: 59},
    { id: 60, application_method_id: 2, conditions_support_id: 60},
    { id: 61, application_method_id: 2, conditions_support_id: 61},

  ##私立幼稚園等保護者補助金-730万以上
    { id: 62, application_method_id: 2, conditions_support_id: 62},
    { id: 63, application_method_id: 2, conditions_support_id: 63},
    { id: 64, application_method_id: 2, conditions_support_id: 64},
    { id: 65, application_method_id: 2, conditions_support_id: 65},
    { id: 66, application_method_id: 2, conditions_support_id: 66},
    { id: 67, application_method_id: 2, conditions_support_id: 67},
    { id: 68, application_method_id: 2, conditions_support_id: 68},
    { id: 69, application_method_id: 2, conditions_support_id: 69},
    { id: 70, application_method_id: 2, conditions_support_id: 70},
    { id: 71, application_method_id: 2, conditions_support_id: 71},
    { id: 72, application_method_id: 2, conditions_support_id: 72},
    { id: 73, application_method_id: 2, conditions_support_id: 73},
  ]
)
