ConditionsSupport.create!(
  [
    { id: 1,
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      payment: 180000,
      payment_limit: 0,
      payment_frequency: 4,
      payment_month: '6月、10月、12月の上旬',
      transfer_destination: '',
      condition_id: 1,
      support_id: 2,
      city_id: 7,
      age_id: 3,
    },
    { id: 2,
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      payment: 180000,
      payment_limit: 0,
      payment_frequency: 4,
      payment_month: '6月、10月、12月の上旬',
      transfer_destination: '',
      condition_id: 2,
      support_id: 2,
      city_id: 7,
      age_id: 3,
    },
    {
      id: 3,
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      payment: 120000,
      payment_limit: 0,
      payment_frequency: 4,
      payment_month: '6月、10月、12月の上旬',
      transfer_destination: '',
      condition_id: 3,
      support_id: 2,
      city_id: 7,
      age_id: 4,
    },
    {
      id: 4,
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      payment: 120000,
      payment_limit: 0,
      payment_frequency: 4,
      payment_month: '6月、10月、12月の上旬',
      transfer_destination: '',
      condition_id: 4,
      support_id: 2,
      city_id: 7,
      age_id: 5,
    },
    {
      id: 5,
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      payment: 180000,
      payment_limit: 0,
      payment_frequency: 4,
      payment_month: '6月、10月、12月の上旬',
      transfer_destination: '',
      condition_id: 5,
      support_id: 2,
      city_id: 7,
      age_id: 3,
    },
    {
      id: 6,
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      payment: 120000,
      payment_limit: 0,
      payment_frequency: 4,
      payment_month: '6月、10月、12月の上旬',
      transfer_destination: '',
      condition_id: 6,
      support_id: 2,
      city_id: 7,
      age_id: 4,
    },
    {
      id: 7,
      url: 'https://www.city.taito.lg.jp/kosodatekyouiku/kosodate/mokutei/teate_josei/teate/jidouteate.html',
      payment: 120000,
      payment_limit: 0,
      payment_frequency: 4,
      payment_month: '6月、10月、12月の上旬',
      transfer_destination: ,
      condition_id: 7,
      support_id: 2,
      city_id: 7,
      age_id: 5,
    },
  ]
)
